sudo: false

language: python

python:
  - 3.5

install:
  - pip install -r requirements.txt

script:
  # Tests
  - python -m unittest discover -v
  # PyLint
  - make lint

notifications:
  email:
    on_success: change
    on_failure: change
