sudo: false

language: r

script:
  # Tests
  - make test

notifications:
  recipients:
    - lei_zhang@berkeley.edu
    - jinhui_xu@berkeley.edu
    - lixiao1995@berkeley.edu
  email:
    on_success: change
    on_failure: change
